/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    ExportSpeedDial: typeof import('./src/components/ui/BaseUIElements/ExportSpeedDial.vue')['default']
    HeaderTitle: typeof import('./src/components/ui/BaseUIElements/HeaderTitle.vue')['default']
    KPICard: typeof import('./src/components/ui/BaseUIElements/KPICard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
