/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideDrawer: typeof import('./src/components/blocks/navigation/AsideDrawer.vue')['default']
    AsideMenu: typeof import('./src/components/features/navigation/VAsideMenu.vue')['default']
    AvatarButton: typeof import('./src/components/ui/navigation/AvatarButton.vue')['default']
    BranchSelect: typeof import('./src/components/features/navigation/VBranchSelect.vue')['default']
    Button: typeof import('./src/components/ui/native/VIconButton.vue')['default']
    ComputerCard: typeof import('./src/components/blocks/computers/VComputerCard.vue')['default']
    ComputerMark: typeof import('./src/components/ui/computers/VComputerMark.vue')['default']
    GroupSelect: typeof import('./src/components/features/navigation/VGroupSelect.vue')['default']
    IconButton: typeof import('./src/components/ui/navigation/IconButton.vue')['default']
    IconWithModal: typeof import('./src/components/ui/computers/IconWithModal.vue')['default']
    MenuDivider: typeof import('./src/components/ui/navigation/MenuDivider.vue')['default']
    NavbarContainer: typeof import('./src/components/features/navigation/NavbarContainer.vue')['default']
    NavbarMenu: typeof import('./src/components/blocks/navigation/VNavbarMenu.vue')['default']
    NotificationDropdown: typeof import('./src/components/features/navigation/VNotificationDropdown.vue')['default']
    RadialProgress: typeof import('./src/components/ui/computers/VRadialProgress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectComputerIcon: typeof import('./src/components/blocks/computers/VSelectComputerIcon.vue')['default']
    SelectComputerIconDialog: typeof import('./src/components/blocks/computers/SelectComputerIconDialog.vue')['default']
    SidebarContainer: typeof import('./src/components/blocks/navigation/SidebarContainer.vue')['default']
    SidebarMenu: typeof import('./src/components/blocks/navigation/AsideDrawer.vue')['default']
    VAsideMenu: typeof import('./src/components/features/navigation/VAsideMenu.vue')['default']
    VBranchSelect: typeof import('./src/components/features/navigation/VBranchSelect.vue')['default']
    VButton: typeof import('./src/components/ui/native/VIconButton.vue')['default']
    VComputerBulkBar: typeof import('./src/components/blocks/computers/VComputerBulkBar.vue')['default']
    VComputerCard: typeof import('./src/components/blocks/computers/VComputerCard.vue')['default']
    VComputerMark: typeof import('./src/components/ui/computers/VComputerMark.vue')['default']
    VComputerRightPanel: typeof import('./src/components/blocks/computers/VComputerRightPanel.vue')['default']
    VCumputerFilters: typeof import('./src/components/ui/computers/VCumputerFilters.vue')['default']
    VGroupSelect: typeof import('./src/components/features/navigation/VGroupSelect.vue')['default']
    VIconButton: typeof import('./src/components/ui/native/VIconButton.vue')['default']
    VNavbarMenu: typeof import('./src/components/blocks/navigation/VNavbarMenu.vue')['default']
    VNotificationDropdown: typeof import('./src/components/features/navigation/VNotificationDropdown.vue')['default']
    VRadialProgress: typeof import('./src/components/ui/computers/VRadialProgress.vue')['default']
    VSelectComputerIcon: typeof import('./src/components/blocks/computers/VSelectComputerIcon.vue')['default']
  }
}
